import csv
import json
import os
path="/Users/shiyingcui/Desktop/second"
for root,dirs,files in os.walk(path):
    for name in files:
        if name.endswith(".json"):
            filename=root+"/"+name
            #print(filename)
            x = json.load(open(filename, "r"))

            ff = csv.writer(open("test.csv", "a"))

            for xx in x:
                ff.writerow([x["response"]["features"]["conditions"],
                             x["response"]["version"],
                             x["response"]["termsofService"],
                             x["current_observation"]["local_tz_long"],
                             x["current_observation"]["visibility_mi"],
                             x["current_observation"]["local_tz_short"],
                             x["current_observation"]["windchill_f"],
                             x["current_observation"]["local_epoch"],
                             x["current_observation"]["pressure_trend"],
                             x["current_observation"]["precip_1hr_in"],
                             x["current_observation"]["temp_f"],
                             x["current_observation"]["heat_index_c"],
                             x["current_observation"]["precip_today_string"],
                             x["current_observation"]["dewpoint_string"],
                             x["current_observation"]["wind_dir"],
                             x["current_observation"]["dewpoint_f"],
                             x["current_observation"]["temp_c"],
                             x["current_observation"]["local_tz_offset"],
                             x["current_observation"]["icon_url"],
                             x["current_observation"]["precip_1hr_metric"],
                             x["current_observation"]["precip_today_metric"],
                             x["current_observation"]["dewpoint_c"],
                             x["current_observation"]["observation_epoch"],
                             x["current_observation"]["observation_time"],
                             x["current_observation"]["pressure_mb"],
                             x["current_observation"]["forecast_url"],
                             x["current_observation"]["wind_string"],
                             x["current_observation"]["wind_mph"],
                             x["current_observation"]["wind_gust_mph"],
                             x["current_observation"]["solarradiation"],
                             x["current_observation"]["temperature_string"],
                             x["current_observation"]["feelslike_c"],
                             x["current_observation"]["visibility_km"],
                             x["current_observation"]["local_time_rfc822"],
                             x["current_observation"]["UV"],
                             x["current_observation"]["observation_time_rfc822"],
                             x["current_observation"]["windchill_string"],
                             x["current_observation"]["precip_today_in"],
                             x["current_observation"]["estimated"],
                             x["current_observation"]["display_location"]["elevation"],
                             x["current_observation"]["display_location"]["country_iso3166"],
                             x["current_observation"]["display_location"]["state"],
                             x["current_observation"]["display_location"]["country"],
                             x["current_observation"]["display_location"]["wmo"],
                             x["current_observation"]["display_location"]["full"],
                             x["current_observation"]["display_location"]["state_name"],
                             x["current_observation"]["display_location"]["zip"],
                             x["current_observation"]["display_location"]["magic"],
                             x["current_observation"]["display_location"]["latitude"],
                             x["current_observation"]["display_location"]["longitude"],
                             x["current_observation"]["display_location"]["city"],
                             x["current_observation"]["heat_index_string"],
                             x["current_observation"]["pressure_in"],
                             x["current_observation"]["feelslike_f"],
                             x["current_observation"]["wind_degrees"],
                             x["current_observation"]["nowcast"],
                             x["current_observation"]["icon"],
                             x["current_observation"]["history_url"],
                             x["current_observation"]["ob_url"],
                             x["current_observation"]["relative_humidity"],
                             x["current_observation"]["feelslike_string"],
                             x["current_observation"]["heat_index_f"],
                             x["current_observation"]["windchill_c"],
                             x["current_observation"]["precip_1hr_string"],
                             x["current_observation"]["weather"],
                             x["current_observation"]["wind_kph"],
                             x["current_observation"]["wind_gust_kph"],
                             x["current_observation"]["image"]["title"],
                             x["current_observation"]["image"]["link"],
                             x["current_observation"]["image"]["url"],
                             x["current_observation"]["observation_location"]["country"],
                             x["current_observation"]["observation_location"]["elevation"],
                             x["current_observation"]["observation_location"]["country_iso3166"],
                             x["current_observation"]["observation_location"]["longitude"],
                             x["current_observation"]["observation_location"]["city"],
                             x["current_observation"]["observation_location"]["state"],
                             x["current_observation"]["observation_location"]["latitude"],
                             x["current_observation"]["observation_location"]["full"],
                             x["current_observation"]["station_id"]])

